<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGcIMdv0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGcIMdv0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGcIMdv0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGcIMdv0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGcIMdv0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GcIMdv0',
    'container.build_id' => '4ab1d5f3',
    'container.build_time' => 1609400257,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGcIMdv0');
