framework:
  messenger:
    transports:
      doctrine_transport:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        options:
          auto_setup: false


    routing:
      # Route your messages to the transports
      App\Message\SmsNotification: doctrine_transport

    buses:
      messenger.bus.default:
        middleware:
          - 'App\Middleware\MailerMiddleware'


