version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: phpRoadmapProject-mysql
        working_dir: /application
        volumes:
            - ./../api:/application
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=jobeet
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - 3308:3306

    webserver:
        image: nginx:alpine
        container_name: phpRoadmapProject-webserver
        working_dir: /application
        volumes:
            - ./../api:/application
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8001:80

    php-fpm:
        build: php-fpm
        container_name: phpRoadmapProject-php-fpm
        working_dir: /application
        volumes:
            - ./../api:/application
            - ./php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
