version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: phpRoadmapProject-mysql
        working_dir: /application
        volumes:
            - ./../App:/application
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=jobeet
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - 3308:3306

    webserver:
        image: nginx:alpine
        container_name: phpRoadmapProject-webserver
        working_dir: /application
        volumes:
            - ./../App:/application
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8001:80

    php-fpm:
        build: php-fpm
        container_name: phpRoadmapProject-php-fpm
        working_dir: /application
        volumes:
            - ./../App:/application
            - ./php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    redis:
        image: redis:alpine
        container_name: backend_api_redis
        environment:
            - REDIS_PASSWORD=password123
            - REDIS_AOF_ENABLED=no
        ports:
                - 6379:6379
        restart: unless-stopped
        volumes:
            - ./redis-data:/application
            - ./redis/redis.conf:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025 # smtp server
            - 8025:8025 # web ui

    second_mailhog:
        image: mailhog/mailhog
        ports:
            - 1027:1025 # smtp server
            - 8027:8025 # web ui

#    mobgoDb
    mongodb:
        image: mongo
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - /home/barry/mongodb/database:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped