<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.rfpzAXz' shared service.

return $this->privates['.service_locator.rfpzAXz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'category' => ['privates', '.errored..service_locator.rfpzAXz.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.rfpzAXz": it references class "App\\Entity\\Category" but no such service exists.'],
    'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService.php', true],
]);
