#index:
#    path: /
#    controller: App\Controller\DefaultController::index
job.export:
  path:       /job/export/{format}/{id}
  controller: App\Controller\JobController::exportFile
  methods:    GET
  requirements:
    id: '\d+'

app_extra:
  resource: .
  type: extra

