<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.rfpzAXz', 'get_ServiceLocator_RfpzAXzService.php', true],
    'App\\Controller\\JobController::list' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\JobController::show' => ['privates', '.service_locator.oTiYhdv', 'get_ServiceLocator_OTiYhdvService.php', true],
    'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.rfpzAXz', 'get_ServiceLocator_RfpzAXzService.php', true],
    'App\\Controller\\JobController:list' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\JobController:show' => ['privates', '.service_locator.oTiYhdv', 'get_ServiceLocator_OTiYhdvService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
